<?php
session_start();

// Jika user belum login, arahkan kembali ke halaman login
if (!isset($_SESSION['U'])) {
    header("Location: ../index.php");
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <!-- Add SweetAlert2 CSS and JS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.19/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.19/dist/sweetalert2.all.min.js"></script>
</head>

<body class="bg-gray-100">
    <div class="flex h-screen bg-gray-200">
        <!-- Sidebar -->
        <div class="w-64 bg-gray-800 text-white p-4">
            <h2 class="text-2xl font-semibold mb-6">Dashboard</h2>
            <ul>
                <li class="mb-4">
                    <a href="user_mana.php" class="block py-2 px-4 rounded hover:bg-gray-700">User Management</a>
                </li>
                <li class="mb-4">
                    <a href="event_mana.php" class="block py-2 px-4 rounded hover:bg-gray-700">Event Management</a>
                </li>
                <!-- Add more menu items here -->
            </ul>
        </div>

        <!-- Main content -->
        <div class="flex-1 overflow-x-hidden overflow-y-auto">
            <!-- Header -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
                    <h1 class="text-3xl font-bold text-gray-900">User Management</h1>
                    <button id="logoutBtn" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
                        Logout
                    </button>
                </div>
            </header>

            <div class="container mx-auto px-4 py-8">
                <div class="bg-white shadow rounded-lg p-6">
                    <div class="flex justify-between items-center mb-6">
                        <button id="addUserBtn" class="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:scale-105">
                            Add New User
                        </button>
                    </div>

                    <div class="font-sans overflow-x-auto">
                        <table id="userTable" class="min-w-full bg-white">
                            <thead class="bg-gray-100 whitespace-nowrap">
                                <tr>
                                    <th class="p-4 text-left text-xs font-semibold text-gray-800">Name</th>
                                    <th class="p-4 text-left text-xs font-semibold text-gray-800">Username</th>
                                    <th class="p-4 text-left text-xs font-semibold text-gray-800">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="whitespace-nowrap">
                                <!-- Rows will be generated by DataTables -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for adding/editing users -->
    <div id="userModal" class="fixed z-50 inset-0 flex items-center justify-center bg-black bg-opacity-50 hidden">
        <div class="bg-white p-6 rounded-lg shadow-lg w-full max-w-md">
            <form id="userForm">
                <input type="hidden" id="userId">
                <div class="mb-4">
                    <label for="username" class="block text-sm font-semibold">Username:</label>
                    <input type="text" id="username" name="username" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
                </div>
                <div class="mb-4">
                    <label for="name" class="block text-sm font-semibold">Name:</label>
                    <input type="text" id="name" name="name" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
                </div>
                <div class="mb-4">
                    <label for="password" class="block text-sm font-semibold">Password:</label>
                    <input type="password" id="password" name="password" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>
                <div class="flex justify-end">
                    <button type="button" class="mr-4 bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-lg" id="cancelBtn">Cancel</button>
                    <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
                </div>
            </form>
        </div>
    </div>


    <script>
        $(document).ready(function() {
            var table = $('#userTable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "../config/server.php",
                    "type": "POST",
                    "data": function(d) {
                        d.action = 'list';
                    }
                },
                "columns": [{
                        "data": "name"
                    },
                    {
                        "data": "username"
                    },
                    {
                        "data": null,
                        "render": function(data, type, row) {
                            return '<button class="edit-btn" data-id="' + row.id_user + '">Edit</button>' +
                                '<button class="delete-btn" data-id="' + row.id_user + '">Delete</button>';
                        }
                    }
                ]
            });

            $('#addUserBtn').on('click', function() {
                $('#userForm')[0].reset();
                $('#userId').val('');
                $('#userModal').removeClass('hidden');
            });

            $('#userForm').on('submit', function(e) {
                e.preventDefault();
                var formData = {
                    action: $('#userId').val() ? 'edit' : 'add',
                    id: $('#userId').val(),
                    username: $('#username').val(),
                    name: $('#name').val(),
                    password: $('#password').val()
                };

                $.ajax({
                    url: '../config/server.php',
                    type: 'POST',
                    data: formData,
                    success: function(response) {
                        table.ajax.reload();
                        $('#userForm')[0].reset();
                        $('#userModal').addClass('hidden');
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            text: response.message || 'User saved successfully'
                        });
                    },
                    error: function(xhr) {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: xhr.responseJSON.error || 'Error saving user'
                        });
                    }
                });
            });

            $('#userTable').on('click', '.delete-btn', function() {
                var data = table.row($(this).closest('tr')).data();
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: '../config/server.php',
                            type: 'POST',
                            data: {
                                action: 'delete',
                                id: data.id_user
                            },
                            success: function(response) {
                                table.ajax.reload();
                                Swal.fire(
                                    'Deleted!',
                                    response.message || 'User deleted successfully',
                                    'success'
                                );
                            },
                            error: function(xhr) {
                                Swal.fire(
                                    'Error!',
                                    xhr.responseJSON.error || 'Error deleting user',
                                    'error'
                                );
                            }
                        });
                    }
                });
            });

            $('#userTable').on('click', '.edit-btn', function() {
                var data = table.row($(this).closest('tr')).data();
                $('#userId').val(data.id_user);
                $('#username').val(data.username);
                $('#name').val(data.name);
                $('#password').val(''); // Clear password field for security
                $('#userModal').removeClass('hidden');
            });

            $('#cancelBtn').on('click', function() {
                $('#userModal').addClass('hidden');
            });

            $('#logoutBtn').on('click', function() {
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You will be logged out!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, log me out!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: '../config/logout.php',
                            type: 'POST',
                            success: function(response) {
                                window.location.href = '../index.php';
                            },
                            error: function() {
                                Swal.fire(
                                    'Error!',
                                    'Error logging out',
                                    'error'
                                );
                            }
                        });
                    }
                });
            });
        });
    </script>
</body>

</html>